### ISSUE TITLE
RTC DEF in Due/SAMD21 

### ISSUE THREAD

**Issue by jecottrell** [JChristensen/MCP79412RTC#2]
EDIT:

Saw that the first issue was the same. Changes that I made below allow compilation. Still working on testing the final result.

I forked and made the changes. Not sure of the protocol for making a pull request.

---

Thanks for taking the time to write this library and the generosity to share it.

It looks like there are two problems that I can see so far with getting your library to work with SAMD21 (Zero) boards.

_BV needs to be defined.

And...

RTC needs to be undefined.

**Comment by jerrylogansquare** [comment]
How do you handle the case where you set the alarm mask to HOUR or MINUTE  (not all), and need to clear the alarm and the current hour or minute hasn't changed yet?  

from the datasheet (note on ALMxIF):

If a match condition still exists when this bit is cleared, it will be set again automatically

**Comment by JChristensen** [comment]
@jerrylogansquare Either disable the alarm (e.g. `RTC.enableAlarm(ALARM_0, ALM_DISABLE)`) or set the alarm to a different value with `RTC.setAlarm()`, or just don't check it until the next interval has elapsed.

**Comment by JChristensen** [comment]
Original issue closed by 0e92bdc
