### ISSUE TITLE
problems when compileing

### ISSUE THREAD

**Issue by immortal-sniper1** [JChristensen/MCP79412RTC#6]
So i went through the example code and tried to compile them and the ones i tried to compile had this problem:
error: 'RTC' was not declared in this scope
   23 |     RTC.set(now());                     // set the RTC from the system time

Compilation error: 'RTC' was not declared in this scope

And I am a bit confused onto how to declare it.
Also i am used to having examples in a lib that work out of the box so it is also a bug in this sense.

**Comment by JChristensen** [comment]
Which board are you compiling for?

**Comment by immortal-sniper1** [comment]
RP pico ( RP2040) both custom one and standard one

**Comment by JChristensen** [comment]
Add the following line near the top of the sketch, after the `#include` statements:
```c++
MCP79412RTC RTC;
```

**Comment by immortal-sniper1** [comment]
ok ill try give me 5 min pls

**Comment by immortal-sniper1** [comment]
ok it seems to compile, ill do a test with the real hard now

**Comment by immortal-sniper1** [comment]
ok so they compile and upload well
the RTC set set the date well and read it well in serial for a time
then i uploaded  TimeRTC and it thinks i am in 1970 even tho date was set for 2022 in the prev code and i have a 3V 2032 cell

**Comment by JChristensen** [comment]
I've only tested the library with AVR architecture, but have not seen that sort of behavior. Sorry I cannot be of further assistance.

**Comment by immortal-sniper1** [comment]
ok thx ill do some more tests and i may be able to figure it out
