### ISSUE TITLE
Feature request: MCP79402 support

### ISSUE THREAD

**Issue by soosp** [JChristensen/MCP79412RTC#7]
What do you think is this possible to extend this library to support MCP79402 RTC chip (especially with EUID-64 support) too?

**Comment by JChristensen** [comment]
Greetings,

I believe the only difference between the MCP7941x and the MCP7940x parts is that the latter do not have 1k bit EEPROM user memory. Therefore the library should work with an MCP79402; have you tried it? Of course, the [EEPROM functions](https://github.com/JChristensen/MCP79412RTC#functions-for-reading-and-writing-eeprom) will need to be avoided.

Cheers! ... jc

**Comment by soosp** [comment]
Hi,

Thank you for the quick answare! I tested my MCP79402 as RTC and EUI64 chip and both of them works well. Thank you!
It was tested on esp8266 platform.

I made a little sketch to demonstrate the GetEUI64() function:
```
// Arduino MCP79412RTC Library
// https://github.com/JChristensen/MCP79412RTC
// GetEUI64.ino
// Example code illustrating how to get EUI-64

#include <MCP79412RTC.h>

MCP79412RTC RTC; // It needed on ESP8266 platform
byte eui[8];
String s = "0x";

void setup()
{
  unsigned int i;
  char buffer[3];
    
  Serial.begin(115200);
  delay(2000);
  Serial.println();

  RTC.getEUI64(eui);
  for (i = 0; i < 8; i++) {
    utoa(eui[i], buffer, 16);
    if ((unsigned int)eui[i] < 16) {
      s += "0";
    }
    s += String(buffer);
  }
  Serial.print("EUI-64: ");
  Serial.println(s);
}

void loop()
{
  yield(); // Feeding watchdog on esp8266
}
```

The result was checked on https://ouilookup.com/ and seems to be a valid Microchip ID.

**Comment by JChristensen** [comment]
Sure thing. Thanks for the feedback.
Happy Holidays from Michigan, USA!
